### ISSUE TITLE
Property 'stringToSPARQLString' does not exist on type 'typeof SparqlService'

### ISSUE THREAD

**Issue by berezovskyi** [jiemakel/khepri#1]
```
TypeScript error: app/scripts/multigooglechartviews-directive.ts(95,199): error TS2339: Property 'stringToSPARQLString' does not exist on type 'typeof SparqlService'.
    at Output.getError (/Users/andrew/code/khepri/node_modules/gulp-typescript/release/output.js:208:19)
    at Output.diagnostic (/Users/andrew/code/khepri/node_modules/gulp-typescript/release/output.js:255:25)
    at ProjectCompiler.inputDone (/Users/andrew/code/khepri/node_modules/gulp-typescript/release/compiler.js:68:33)
    at CompileStream.end (/Users/andrew/code/khepri/node_modules/gulp-typescript/release/main.js:52:31)
    at DestroyableTransform.onend (/Users/andrew/code/khepri/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:495:10)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at endReadableNT (/Users/andrew/code/khepri/node_modules/gulp-sourcemaps/node_modules/readable-stream/lib/_stream_readable.js:865:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
```

**Comment by jiemakel** [comment]
can't reproduce, was this cause by the outdated build environment?
